version: 2
updates:
- package-ecosystem: nuget
  directory: "/StackTraceBeautify/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/StackTraceBeautify.Tests/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10